language: python 
python:
- "3.6" 
- "3.7"
env: 
- DJANGO=2.0 DB=postgres
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
- pip install psycopg2-binary
- pip install django-cors-headers
- pip install pycryptodome
- pip install djangorestframework
- pip install requests
- pip install django-filter
- pip install django-rest-swagger
services:
  - postgresql

addons:
  postgresql: "9.6"
global:
  - PGPORT=5432

before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - python manage.py migrate

script: 
- python manage.py test
