language: python 

python: 
- "2.7"
- "3.6"
env: 
- DJANGO=2.0 db=postgres
- DJANGO=1.11.24 db=postgres

before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
- pip install psycopg2-binary
- pip install django-cors-headers
- pip install pycryptodome
- pip install djangorestframework
- pip install requests
- pip install django-filter
- pip install django-rest-swagger
services:
  - postgresql
branches:
only:
- master

addons:
  postgresql: "9.6"
global:
  - PGPORT=5432

before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - python manage.py migrate

script: 
- python manage.py test
